name: Download and Send Video

on:
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        pip install requests aiogram

    - name: Run Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        VIDEO_URL: ${{ secrets.VIDEO_URL }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        python bot.py
        
